version: "3.9"

services:   
  g-auth:
    hostname: g-auth
    image: g-auth:latest
    build:
      context: ./../../microservices/g-auth
      dockerfile: Dockerfile
    depends_on:
      - l-rabbitmq
    networks:
      microservices:
 
networks:
  microservices:
    name: msc
  
      
 # export COMPOSE_PROJECT_NAME=cb-msc
 # docker compose up --build
  